server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: produit-service
          uri: lb://PRODUIT-SERVICE
          predicates:
            - Path=/api/produits/**
        - id: stock-service
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/api/stocks/**
        - id: fournisseur-service
          uri: lb://FOURNISSEUR-SERVICE
          predicates:
            - Path=/api/fournisseurs/**
        - id: commande-service
          uri: lb://COMMANDE-SERVICE
          predicates:
            - Path=/api/commandes/**
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/clients/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
